// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARam0GDKvru2fFbE-d_4iAnlU0myn_AT0',
    appId: '1:494850597781:web:323be4c579765e80498c9c',
    messagingSenderId: '494850597781',
    projectId: 'test-9bb09',
    authDomain: 'test-9bb09.firebaseapp.com',
    databaseURL: 'https://test-9bb09.firebaseio.com',
    storageBucket: 'test-9bb09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2sxm7RY-SXhf7fxPedLRt-SzaCDWvYd8',
    appId: '1:494850597781:android:bc1216b96821028e498c9c',
    messagingSenderId: '494850597781',
    projectId: 'test-9bb09',
    databaseURL: 'https://test-9bb09.firebaseio.com',
    storageBucket: 'test-9bb09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQKKCyrDcFI829jln3K9lroEjqpnMD7ic',
    appId: '1:494850597781:ios:fa309e1742a2e6d3498c9c',
    messagingSenderId: '494850597781',
    projectId: 'test-9bb09',
    databaseURL: 'https://test-9bb09.firebaseio.com',
    storageBucket: 'test-9bb09.appspot.com',
    iosBundleId: 'com.example.firebaseFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQKKCyrDcFI829jln3K9lroEjqpnMD7ic',
    appId: '1:494850597781:ios:a67c8f129f240d7e498c9c',
    messagingSenderId: '494850597781',
    projectId: 'test-9bb09',
    databaseURL: 'https://test-9bb09.firebaseio.com',
    storageBucket: 'test-9bb09.appspot.com',
    iosBundleId: 'com.example.firebaseFlutterApp.RunnerTests',
  );
}
